"""
분석 결과를 바탕으로 최적화 Dockerfile 초안 생성.

전략:
  1. Patch가 있는 Finding: 해당 줄을 직접 교체 (예: FROM 이미지 교체).
  2. Patch 없는 Finding: 해당 줄 위에 # [imgadvisor] 주석으로 권고 사항 삽입.
  3. SINGLE_STAGE_BUILD Finding: 파일 하단에 멀티-스테이지 템플릿을 블록으로 추가.

줄 번호 처리:
  패치와 주석 삽입 모두 줄 번호 내림차순으로 처리한다.
  위쪽 줄부터 수정하면 아래 줄의 인덱스가 밀려서 오프셋이 틀어지기 때문이다.
"""
from __future__ import annotations

from imgadvisor.models import DockerfileIR, Finding, Severity

# 생성된 Dockerfile 상단에 붙는 안내 헤더
_HEADER = """\
# ============================================================
# Generated by imgadvisor — pre-build optimization advisor
# https://github.com/0206pdh/dockimage_scanner
#
# NOTE: auto-generated — review before deploying to production.
# ============================================================
"""


def recommend(ir: DockerfileIR, findings: list[Finding]) -> str:
    """
    Finding 목록을 참고해 최적화된 Dockerfile 내용을 문자열로 반환한다.

    처리 순서:
    1. Patch가 있는 Finding을 내림차순으로 적용 (줄 오프셋 드리프트 방지)
    2. Patch 없는 Finding에 inline 주석 삽입
    3. SINGLE_STAGE_BUILD가 있으면 파일 끝에 멀티-스테이지 템플릿 추가
    4. 헤더 + 본문 + 접미사를 합쳐서 반환

    Args:
        ir      : 원본 Dockerfile IR (raw_lines 사용)
        findings: analyze()가 반환한 Finding 목록

    Returns:
        최적화된 Dockerfile 내용 (문자열)
    """
    multi_finding = next(
        (f for f in findings if f.rule_id == "SINGLE_STAGE_BUILD"), None
    )
    generated_multistage = _extract_multistage_template(multi_finding) if multi_finding else None
    if generated_multistage is not None:
        return _HEADER + "\n" + generated_multistage + "\n"

    lines = list(ir.raw_lines)  # 원본 줄 목록 복사 (직접 수정)

    # ── 1단계: 줄 직접 교체 패치 적용 ─────────────────────────────────────────
    # 내림차순 정렬: 아래쪽 줄부터 수정해야 위쪽 줄 번호가 유지된다
    patches = [f.patch for f in findings if f.patch is not None]
    patches.sort(key=lambda p: p.line_no, reverse=True)

    for patch in patches:
        idx = patch.line_no - 1  # 0-based 인덱스로 변환
        # 현재 줄 내용이 패치 대상과 일치할 때만 교체 (안전 장치)
        if 0 <= idx < len(lines) and lines[idx] == patch.old_text:
            lines[idx] = patch.new_text

    # Base image가 Alpine 계열로 바뀌는 경우, 단순 apt install 패턴은 apk add로
    # 함께 변환해 validate/build 단계에서 즉시 깨지는 Dockerfile 생성을 줄인다.
    _apply_package_manager_compatibility_fixes(lines, ir, findings)

    # ── 2단계: 주석 삽입 ───────────────────────────────────────────────────────
    _insert_comments(lines, findings)

    body = "\n".join(lines)

    # ── 3단계: 멀티-스테이지 템플릿 추가 ──────────────────────────────────────
    suffix = ""
    if multi_finding:
        suffix = "\n\n" + _format_multistage_block(multi_finding)

    return _HEADER + "\n" + body + suffix


def _insert_comments(lines: list[str], findings: list[Finding]) -> None:
    """
    Patch 없는 Finding마다 # [imgadvisor] 주석을 해당 줄 바로 위에 삽입한다.

    SINGLE_STAGE_BUILD는 파일 하단 블록으로 별도 처리하므로 여기서 제외한다.
    삽입은 줄 번호 내림차순으로 수행해 위쪽 줄의 인덱스 드리프트를 방지한다.

    삽입되는 주석 형식:
        # [imgadvisor:FAIL] RULE_ID
        #   description
        #   recommendation (최대 3줄)
    """
    # Patch 없고 줄 번호 있고 단일 스테이지 규칙이 아닌 Finding만 처리
    no_patch = [
        f for f in findings
        if f.patch is None and f.line_no is not None and f.rule_id != "SINGLE_STAGE_BUILD"
    ]
    # 내림차순: 아래 줄부터 삽입해야 위쪽 인덱스가 유지됨
    no_patch.sort(key=lambda f: f.line_no or 0, reverse=True)

    for f in no_patch:
        idx = (f.line_no or 1) - 1  # 0-based 변환
        if not (0 <= idx < len(lines)):
            continue
        severity_tag = "FAIL" if f.severity == Severity.HIGH else "WARN"
        comment_lines = [
            f"# [imgadvisor:{severity_tag}] {f.rule_id}",
            f"#   {f.description}",
        ]
        # 권고사항 최대 3줄만 삽입 (너무 길어지지 않도록)
        for rec_line in f.recommendation.splitlines()[:3]:
            comment_lines.append(f"#   {rec_line}")
        # 해당 줄 앞에 주석 삽입
        lines[idx:idx] = comment_lines


def _format_multistage_block(finding: Finding) -> str:
    """
    SINGLE_STAGE_BUILD Finding의 권고 사항을 주석 블록으로 포맷해서 반환한다.

    파일 하단에 추가되어 사용자가 참고할 수 있는 멀티-스테이지 템플릿을 제공한다.
    """
    lines = [
        "# ============================================================",
        "# [imgadvisor] multi-stage build suggestion",
        "# rewrite your Dockerfile using the template below",
        "# ============================================================",
        "#",
    ]
    for line in finding.recommendation.splitlines():
        lines.append(f"# {line}")
    return "\n".join(lines) + "\n"


def _extract_multistage_template(finding: Finding | None) -> str | None:
    """
    Turn SINGLE_STAGE_BUILD recommendation text into an actual Dockerfile body.

    The recommendation format is:
        convert to multi-stage build:

          <template lines...>

    If the template still contains obvious placeholders, return None so the
    recommender can fall back to the older comment-only behavior.
    """
    if finding is None:
        return None

    lines = finding.recommendation.splitlines()
    if not lines or not lines[0].startswith("convert to multi-stage build:"):
        return None

    template_lines = lines[2:] if len(lines) >= 3 else []
    cleaned = [line[2:] if line.startswith("  ") else line for line in template_lines]
    template = "\n".join(cleaned).strip()
    if not template:
        return None

    if "<build-image>" in template or "<runtime-image-slim>" in template or "<app/entrypoint>" in template:
        return None

    return template


def _apply_package_manager_compatibility_fixes(
    lines: list[str],
    ir: DockerfileIR,
    findings: list[Finding],
) -> None:
    """
    Rewrite known package-manager commands after a base-image swap.

    Current scope is intentionally narrow:
    - final stage only
    - Alpine runtime selected by BASE_IMAGE_NOT_OPTIMIZED patch
    - simple apt install blocks that can be translated safely
    """
    if ir.final_stage is None:
        return

    alpine_selected = any(
        finding.rule_id == "BASE_IMAGE_NOT_OPTIMIZED"
        and finding.patch is not None
        and ("-alpine" in finding.patch.new_text or "FROM alpine:" in finding.patch.new_text)
        for finding in findings
    )
    if not alpine_selected:
        return

    for instr in sorted(ir.final_stage.run_instructions, key=lambda item: item.line_no, reverse=True):
        replacement = _translate_apt_run_to_apk(instr.arguments)
        if replacement is None:
            continue

        start_idx = instr.line_no - 1
        end_idx = _find_instruction_end_index(lines, start_idx)
        if not (0 <= start_idx <= end_idx < len(lines)):
            continue

        lines[start_idx:end_idx + 1] = replacement.splitlines()


def _find_instruction_end_index(lines: list[str], start_idx: int) -> int:
    """Return the inclusive end index of a backslash-continued Dockerfile instruction."""
    idx = start_idx
    while idx < len(lines) - 1 and lines[idx].rstrip().endswith("\\"):
        idx += 1
    return idx


def _translate_apt_run_to_apk(run_text: str) -> str | None:
    """
    Convert a simple apt install RUN into an Alpine apk add RUN.

    The translator is conservative. If package extraction or mapping is not
    straightforward, it returns None and leaves the instruction untouched.
    """
    import re

    normalized = " ".join(run_text.strip().split())
    match = re.search(r"(?:apt-get|apt)\s+install\s+(.+)", normalized, re.IGNORECASE)
    if not match:
        return None

    tail = re.split(r"\s*(?:&&|;|\|\|)\s*", match.group(1), maxsplit=1)[0].strip()
    if not tail:
        return None

    apt_to_apk = {
        "build-essential": "build-base",
        "libpq-dev": "postgresql-dev",
        "libssl-dev": "openssl-dev",
        "pkg-config": "pkgconf",
    }
    passthrough = {
        "bash",
        "ca-certificates",
        "coreutils",
        "curl",
        "gcc",
        "g++",
        "git",
        "grep",
        "libffi-dev",
        "make",
        "musl-dev",
        "openssl",
        "python3-dev",
        "sed",
        "tar",
        "unzip",
        "zip",
    }

    packages: list[str] = []
    for token in tail.split():
        if token.startswith("-"):
            continue
        mapped = apt_to_apk.get(token, token if token in passthrough else None)
        if mapped is None:
            return None
        packages.append(mapped)

    if not packages:
        return None

    if "build-base" in packages:
        packages = [pkg for pkg in packages if pkg not in {"gcc", "g++", "make"}]

    deduped: list[str] = []
    for package in packages:
        if package not in deduped:
            deduped.append(package)

    if len(deduped) == 1:
        return f"RUN apk add --no-cache {deduped[0]}"

    return "RUN apk add --no-cache \\\n" + " \\\n".join(f"    {pkg}" for pkg in deduped)
